language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - GUZZLE_VERSION="~4.0"
  - GUZZLE_VERSION="~5.0"
  - GUZZLE_VERSION="~6.0"

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  exclude:
    - env: GUZZLE_VERSION="~6.0"
      php: 5.4

before_script:
  - composer self-update
  - composer require guzzlehttp/guzzle:${GUZZLE_VERSION} -n
  - composer install --dev

script:
  - php bin/phpunit tests/
